title: Associate Data Analyst Kenny LIm # your name (or website title) here
logo: "/images/KennyLimpic.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  Capstone projects portfolio
  <br><br>
  In this page, I featured my capstone projects that I have embarked using <strong> Excel Dashboard, <p> Analyse Data with SQL,<strong>
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
