title: Associate Data Analyst by Kenny Lim # your name (or website title) here
logo: "/images/KennyLimpic.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  Capstone projects portfolio
  <br><br>
  In this page, I featured my capstone projects that I have embarked using <strong> Excel Dashboard, MS SQL, PowerBI and Python(jupyter)</strong>
  <br><br>
  <a href="https://www.linkedin.com/in/kennylimba" target="_blank">View My LinkedIn Profile</a> 
  <p style="font-size:12px">Kennylim.67@gmail.com</p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
